name:                epi-sim
version:             0.1.5.1
github:              "azarebski/epi-sim"
license:             BSD3
author:              "Alexander Zarebski"
maintainer:          "aezarebski@gmail.com"
copyright:           "2020 Alexander Zarebski"

extra-source-files:
- README.md
- ChangeLog.md
- vis/*.json

synopsis:            A tool for simulating epidemics.

description:         Please see the README on GitHub at <https://bitbucket.org/azarebski/epi-sim/src/master/README.md>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- mwc-random
- vector
- trifecta

library:
  source-dirs: src

executables:
  epi-sim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - epi-sim

tests:
  epi-sim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - epi-sim
    - hspec
